/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Issue browser-memory mutation configuration */
    get: operations['bootstrap']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/commit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Commit one reviewed active journal prefix */
    post: operations['commitProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Report persistent profile service health */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/mutations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply one persistent profile action */
    post: operations['mutateProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/redo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['redoProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review pending operation summaries */
    post: operations['reviewProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/review/targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review one bounded affected-target window */
    post: operations['reviewProfileTargets']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/undo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['undoProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/view': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Project one stateless read-only view */
    post: operations['projectView']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/view/transition': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply one stateless read-only view transition */
    post: operations['transitionView']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActiveDateRange: {
      from: string
      to: string
    }
    ActiveFilters: {
      date_range?: components['schemas']['ActiveDateRange']
      show_hidden: boolean
      show_transfers: boolean
    }
    AggregateRow: {
      /** Format: int64 */
      count: number
      dimension: string
      flags: components['schemas']['Flags']
      identity: string
      /** Format: int64 */
      index: number
      label: string
      period?: components['schemas']['Period']
      /** Format: int64 */
      share_tenths: number
      top_category?: string
      /** Format: int64 */
      top_category_percent?: number
      total: components['schemas']['Money']
    }
    Bootstrap: {
      base_path: string
      canonical_url: string
      mutation_token: string
      revision: string
      /** Format: date-time */
      token_expires_at: string
      version: string
    }
    Breadcrumb: {
      dimension: string
      label: string
    }
    Capability: {
      available: boolean
      category: string
      description: string
      id: string
      key_display?: string
    }
    Chart: {
      marks?: components['schemas']['ChartMark'][] | null
      summary?: components['schemas']['Statistics'][] | null
    }
    ChartMark: {
      amount: components['schemas']['Money']
      identity: string
      /** Format: int64 */
      index: number
      label: string
      /** Format: int64 */
      plot_ratio: number
    }
    CommitBody: {
      expected_revision: string
      query: string
      reviewed_revision: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    DetailRow: {
      account: string
      amount: components['schemas']['Money']
      category: string
      date: string
      flags: components['schemas']['Flags']
      group: string
      identity: string
      /** Format: int64 */
      index: number
      merchant: string
    }
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string
      /** @description Error message text */
      message?: string
      /** @description The value at the given location */
      value?: unknown
    }
    ErrorModel: {
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    Flags: {
      hidden: boolean
      pending: boolean
      selected: boolean
    }
    Health: {
      api_schema_version: string
      base_path: string
      data_status: string
      pending: components['schemas']['PendingSummary']
      read_only: boolean
      revision: string
      version: string
    }
    Money: {
      currency: string
      decimal: string
      display: string
      minor: string
      /** Format: int32 */
      scale: number
    }
    MutationBody: {
      action: string
      expected_revision: string
      input: components['schemas']['MutationInput']
      query: string
      selection?: string
      target?: components['schemas']['TransitionTarget']
      version: string
      window: components['schemas']['Window']
    }
    MutationInput: {
      destination_id?: string
      entity_id?: string
      group_id?: string
      label?: string
      replacement_id?: string
      scope?: string
      taxonomy?: string
    }
    MutationResponse: {
      canonical_query: string
      pending: components['schemas']['PendingSummary']
      projection: components['schemas']['Projection']
      revision: string
      selection: components['schemas']['SelectionDisposition']
      version: string
    }
    PendingSummary: {
      /** Format: int64 */
      active_operations: number
      /** Format: int64 */
      affected_transactions: number
      /** Format: int64 */
      inactive_operations: number
    }
    Period: {
      /** Format: int64 */
      day?: number
      granularity: string
      /** Format: int64 */
      month?: number
      /** Format: int64 */
      year: number
    }
    Problem: {
      code: string
      current_revision?: string
      detail: string
      selection?: components['schemas']['SelectionDisposition']
      /** Format: int64 */
      status: number
      title: string
      /**
       * Format: uri
       * @default about:blank
       */
      type: string
    }
    Projection: {
      aggregate_rows?: components['schemas']['AggregateRow'][] | null
      api_schema_version: string
      breadcrumb_text: string
      breadcrumbs: components['schemas']['Breadcrumb'][] | null
      canonical_query: string
      capabilities: components['schemas']['Capability'][] | null
      chart: components['schemas']['Chart']
      detail_rows?: components['schemas']['DetailRow'][] | null
      filters: components['schemas']['ActiveFilters']
      pending: components['schemas']['PendingSummary']
      projection_schema_version: string
      revision: string
      selection: string
      statistics: components['schemas']['Statistics'][] | null
      status?: string
      /** Format: int64 */
      total_rows: number
      view: components['schemas']['ViewMetadata']
      warnings?: components['schemas']['Warning'][] | null
      window: components['schemas']['ReturnedWindow']
    }
    ReturnedWindow: {
      /** Format: int64 */
      count: number
      /** Format: int64 */
      limit: number
      /** Format: int64 */
      offset: number
    }
    ReviewBody: {
      expected_revision: string
      version: string
    }
    ReviewOperation: {
      active: boolean
      /** Format: int64 */
      affected_count: number
      after?: string
      before?: string
      operation_id: string
      taxonomy_effect?: string
      type: string
    }
    ReviewResponse: {
      active_operations: components['schemas']['ReviewOperation'][] | null
      inactive_operations: components['schemas']['ReviewOperation'][] | null
      operation_id?: string
      pending: components['schemas']['PendingSummary']
      revision: string
      targets?: components['schemas']['ReviewTarget'][] | null
      version: string
      window: components['schemas']['ReturnedWindow']
    }
    ReviewTarget: {
      category: string
      date: string
      hidden: boolean
      merchant: string
    }
    ReviewTargetsBody: {
      expected_revision: string
      operation_id: string
      version: string
      window: components['schemas']['Window']
    }
    RevisionBody: {
      expected_revision: string
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    SelectionDisposition: {
      kind: string
      value: string
    }
    Statistics: {
      /** Format: int64 */
      count: number
      currency: string
      in: components['schemas']['Money']
      net: components['schemas']['Money']
      out: components['schemas']['Money']
      /** Format: int32 */
      scale: number
    }
    TransitionBody: {
      action: string
      filters?: components['schemas']['TransitionFilters']
      query: string
      search?: string
      selection?: string
      target?: components['schemas']['TransitionTarget']
      window: components['schemas']['Window']
    }
    TransitionDateRange: {
      /** Format: date */
      end: string
      /** Format: date */
      start: string
    }
    TransitionFilters: {
      date_range?: components['schemas']['TransitionDateRange']
      show_hidden: boolean
      show_transfers: boolean
    }
    TransitionTarget: {
      identity: string
      kind: string
    }
    ViewBody: {
      query: string
      selection?: string
      window: components['schemas']['Window']
    }
    ViewMetadata: {
      grouping: string
      mode: string
      search?: string
      sort_direction: string
      sort_field: string
      time_granularity: string
    }
    Warning: {
      code: string
      detail: string
    }
    Window: {
      /**
       * Format: int64
       * @default 200
       */
      limit: number
      /**
       * Format: int64
       * @default 0
       */
      offset: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  bootstrap: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Bootstrap']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  commitProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CommitBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  mutateProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MutationBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  redoProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  reviewProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  reviewProfileTargets: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewTargetsBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  undoProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  projectView: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ViewBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Projection']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  transitionView: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Projection']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
}
