/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Issue browser-memory mutation configuration */
    get: operations['bootstrap']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List local profiles */
    get: operations['listProfiles']
    put?: never
    /** Create a pristine local profile */
    post: operations['createProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Activate a catalog profile and return its durable identity */
    post: operations['activateProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Issue profile-scoped browser mutation configuration */
    get: operations['profileBootstrap']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel one newly created pristine profile */
    post: operations['cancelNewProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/commit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Commit one reviewed active journal prefix */
    post: operations['commitProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/duplicates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Project bounded duplicate transaction groups */
    post: operations['projectProfileDuplicates']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/editor-catalog': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Load bounded active editor choices */
    post: operations['editorCatalog']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Report persistent profile service health */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/mutations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply one persistent profile action */
    post: operations['mutateProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/onboarding/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start profile onboarding */
    post: operations['startProfileOnboarding']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/onboarding/{attempt_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel profile onboarding */
    post: operations['cancelProfileOnboarding']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/onboarding/{attempt_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read credential-blind onboarding status */
    get: operations['profileOnboardingStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/onboarding/{attempt_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit one onboarding transition */
    post: operations['submitProfileOnboarding']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh one complete provider snapshot */
    post: operations['refreshProvider']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/refresh/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm one suspicious provider refresh candidate */
    post: operations['confirmProviderRefresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Report counts-only provider refresh status */
    get: operations['providerStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/write-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Report counts-only provider write status */
    get: operations['providerWriteStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/write/pause': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Control one durable provider write batch */
    post: operations['pauseProviderWrite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/write/reconcile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reconcile one durable provider write batch */
    post: operations['reconcileProviderWrite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/write/reconcile/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reconcile one durable provider write batch */
    post: operations['confirmProviderWriteReconcile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/provider/write/resume': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Control one durable provider write batch */
    post: operations['resumeProviderWrite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/recovery': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Preview or confirm profile recovery */
    post: operations['recoverProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/redo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['redoProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review pending operation summaries */
    post: operations['reviewProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/review/targets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review one bounded affected-target window */
    post: operations['reviewProfileTargets']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/undo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['undoProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/view': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Project one stateless read-only view */
    post: operations['projectView']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{profile_id}/view/transition': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply one stateless read-only view transition */
    post: operations['transitionView']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActiveDateRange: {
      from: string
      to: string
    }
    ActiveFilters: {
      date_range?: components['schemas']['ActiveDateRange']
      show_hidden: boolean
      show_transfers: boolean
    }
    AggregateRow: {
      /** Format: int64 */
      count: number
      dimension: string
      flags: components['schemas']['Flags']
      identity: string
      /** Format: int64 */
      index: number
      label: string
      period?: components['schemas']['Period']
      /** Format: int64 */
      share_tenths: number
      top_category?: string
      /** Format: int64 */
      top_category_percent?: number
      total: components['schemas']['Money']
    }
    Bootstrap: {
      base_path: string
      canonical_url: string
      mutation_token: string
      revision: string
      /** Format: date-time */
      token_expires_at: string
      version: string
    }
    Breadcrumb: {
      dimension: string
      label: string
    }
    Capability: {
      available: boolean
      category: string
      description: string
      id: string
      key_display?: string
      reason?: string
    }
    Chart: {
      marks?: components['schemas']['ChartMark'][] | null
      summary?: components['schemas']['Statistics'][] | null
    }
    ChartMark: {
      amount: components['schemas']['Money']
      identity: string
      /** Format: int64 */
      index: number
      label: string
      /** Format: int64 */
      plot_ratio: number
    }
    CommitBody: {
      expected_revision: string
      query: string
      reviewed_revision: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    DetailRow: {
      account: string
      amount: components['schemas']['Money']
      category: string
      date: string
      flags: components['schemas']['Flags']
      group: string
      identity: string
      /** Format: int64 */
      index: number
      merchant: string
    }
    DuplicateBody: {
      expected_revision: string
      group_window: components['schemas']['Window']
      query: string
      row_window: components['schemas']['Window']
      selection?: string
      version: string
    }
    DuplicateGroup: {
      /** Format: int64 */
      number: number
      rows: components['schemas']['DuplicateRow'][] | null
    }
    DuplicateResponse: {
      canonical_query: string
      group_window: components['schemas']['ReturnedWindow']
      groups: components['schemas']['DuplicateGroup'][] | null
      revision: string
      row_window: components['schemas']['ReturnedWindow']
      selection: string
      /** Format: int64 */
      selection_count: number
      status?: string
      /** Format: int64 */
      total_groups: number
      /** Format: int64 */
      total_transactions: number
      version: string
    }
    DuplicateRow: {
      account: string
      amount: components['schemas']['Money']
      category: string
      date: string
      flags: components['schemas']['Flags']
      group: string
      /** Format: int64 */
      group_number: number
      matching_label: string
      merchant: string
      target: components['schemas']['TransitionTarget']
    }
    EditorCatalogBody: {
      expected_revision: string
      version: string
    }
    EditorCatalogResponse: {
      categories: components['schemas']['EditorChoice'][] | null
      groups: components['schemas']['EditorChoice'][] | null
      merchants: components['schemas']['EditorChoice'][] | null
      revision: string
      version: string
    }
    EditorChoice: {
      id: string
      label: string
      parent_id?: string
      protected: boolean
    }
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string
      /** @description Error message text */
      message?: string
      /** @description The value at the given location */
      value?: unknown
    }
    ErrorModel: {
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    Flags: {
      hidden: boolean
      pending: boolean
      selected: boolean
    }
    Health: {
      api_schema_version: string
      base_path: string
      data_status: string
      pending: components['schemas']['PendingSummary']
      read_only: boolean
      revision: string
      version: string
    }
    Money: {
      currency: string
      decimal: string
      display: string
      minor: string
      /** Format: int32 */
      scale: number
    }
    MutationBody: {
      action: string
      expected_revision: string
      input: components['schemas']['MutationInput']
      query: string
      selection?: string
      target?: components['schemas']['TransitionTarget']
      version: string
      window: components['schemas']['Window']
    }
    MutationInput: {
      destination_id?: string
      entity_id?: string
      group_id?: string
      label?: string
      replacement_id?: string
      scope?: string
      taxonomy?: string
    }
    MutationResponse: {
      canonical_query: string
      pending: components['schemas']['PendingSummary']
      projection: components['schemas']['Projection']
      provider_write?: components['schemas']['ProviderWriteStatusResponse']
      revision: string
      selection: components['schemas']['SelectionDisposition']
      version: string
    }
    OnboardingCancelBody: {
      /** Format: int64 */
      expected_state_version: number
      /** Format: int32 */
      protocol_version: number
    }
    OnboardingCredentialsInput: {
      account_password: string
      confirmation: string
      email: string
      password: string
      totp_secret: string
    }
    OnboardingFailureResponse: {
      can_reenter: boolean
      can_retry: boolean
      code: string
      message: string
    }
    OnboardingProgressResponse: {
      /** Format: int64 */
      attempt: number
      /** Format: int64 */
      elapsed_ms: number
      /** Format: int64 */
      fetched: number
      partition: string
      /** Format: int64 */
      pass: number
      phase: string
      /** Format: int64 */
      total: number
    }
    OnboardingSettingsInput: {
      currency: string
      /** Format: int32 */
      scale: number
    }
    OnboardingStartBody: {
      month_to_date: boolean
      /** Format: int32 */
      protocol_version: number
      settings?: components['schemas']['OnboardingSettingsInput']
    }
    OnboardingStatusResponse: {
      attempt_id: string
      failure?: components['schemas']['OnboardingFailureResponse']
      profile_id: string
      progress?: components['schemas']['OnboardingProgressResponse']
      /** Format: int32 */
      protocol_version: number
      provider_kind: string
      settings?: components['schemas']['OnboardingSettingsInput']
      state: string
      /** Format: int64 */
      state_version: number
    }
    OnboardingSubmitBody: {
      action: string
      credentials?: components['schemas']['OnboardingCredentialsInput']
      /** Format: int64 */
      expected_state_version: number
      /** Format: int32 */
      protocol_version: number
      settings?: components['schemas']['OnboardingSettingsInput']
      unlock?: components['schemas']['OnboardingUnlockInput']
    }
    OnboardingUnlockInput: {
      account_password: string
    }
    PendingSummary: {
      /** Format: int64 */
      active_operations: number
      /** Format: int64 */
      affected_transactions: number
      /** Format: int64 */
      inactive_operations: number
    }
    Period: {
      /** Format: int64 */
      day?: number
      granularity: string
      /** Format: int64 */
      month?: number
      /** Format: int64 */
      year: number
    }
    Problem: {
      code: string
      current_revision?: string
      detail: string
      provider?: components['schemas']['ProviderStatusResponse']
      provider_write?: components['schemas']['ProviderWriteStatusResponse']
      provider_write_confirmation_token?: string
      selection?: components['schemas']['SelectionDisposition']
      /** Format: int64 */
      status: number
      title: string
      /**
       * Format: uri
       * @default about:blank
       */
      type: string
    }
    ProfileActivateBody: {
      key: string
      /** @enum {string} */
      provider_kind?: 'monarch' | 'local'
      version: string
    }
    ProfileCancelBody: {
      version: string
    }
    ProfileCancelResponse: {
      removed: boolean
      version: string
    }
    ProfileCatalogResponse: {
      profiles: components['schemas']['ProfileSummary'][] | null
      version: string
    }
    ProfileCreateBody: {
      display_name: string
      /** @enum {string} */
      provider_kind: 'monarch' | 'local'
      version: string
    }
    ProfileResponse: {
      profile: components['schemas']['ProfileSummary']
      version: string
    }
    ProfileSummary: {
      display_name: string
      id?: string
      key: string
      provider_kind: string
      status: string
    }
    Projection: {
      aggregate_rows?: components['schemas']['AggregateRow'][] | null
      api_schema_version: string
      breadcrumb_text: string
      breadcrumbs: components['schemas']['Breadcrumb'][] | null
      canonical_query: string
      capabilities: components['schemas']['Capability'][] | null
      chart: components['schemas']['Chart']
      detail_rows?: components['schemas']['DetailRow'][] | null
      filters: components['schemas']['ActiveFilters']
      pending: components['schemas']['PendingSummary']
      projection_schema_version: string
      revision: string
      selection: string
      /** Format: int64 */
      selection_count: number
      statistics: components['schemas']['Statistics'][] | null
      status?: string
      /** Format: int64 */
      total_rows: number
      view: components['schemas']['ViewMetadata']
      warnings?: components['schemas']['Warning'][] | null
      window: components['schemas']['ReturnedWindow']
    }
    ProviderConfirmationBody: {
      confirmation_token: string
      manual: boolean
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    ProviderProgress: {
      /** Format: int64 */
      fetched: number
      /** Format: int64 */
      total: number
    }
    ProviderRefreshBody: {
      manual: boolean
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    ProviderRefreshResponse: {
      generation: string
      projection: components['schemas']['Projection']
      revision: string
      selection: components['schemas']['SelectionDisposition']
      status: components['schemas']['ProviderStatusResponse']
      version: string
    }
    ProviderRefreshSummary: {
      /** Format: int64 */
      discarded_redo_operations: number
      /** Format: int64 */
      imported_accounts: number
      /** Format: int64 */
      imported_categories: number
      /** Format: int64 */
      imported_groups: number
      /** Format: int64 */
      imported_merchants: number
      /** Format: int64 */
      imported_transactions: number
      /** Format: int64 */
      rebased_hide_targets: number
      /** Format: int64 */
      removed_operations: number
      /** Format: int64 */
      removed_targets: number
      /** Format: int64 */
      removed_transactions: number
      /** Format: int64 */
      retained_operations: number
    }
    ProviderStatusResponse: {
      capability: components['schemas']['Capability']
      code?: string
      confirmation_token?: string
      generation: string
      /** Format: date-time */
      last_success?: string
      /** Format: date-time */
      next_eligible?: string
      owner_instance_id?: string
      owner_renderer?: string
      progress: components['schemas']['ProviderProgress']
      revision: string
      summary: components['schemas']['ProviderRefreshSummary']
      version: string
    }
    ProviderWriteConfirmationBody: {
      confirmation_token: string
      expected_batch_version: string
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    ProviderWriteControlBody: {
      expected_batch_version: string
      version: string
    }
    ProviderWriteReconcileBody: {
      expected_batch_version: string
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    ProviderWriteResponse: {
      projection?: components['schemas']['Projection']
      selection?: components['schemas']['SelectionDisposition']
      status: components['schemas']['ProviderWriteStatusResponse']
    }
    ProviderWriteStatusResponse: {
      actions: string[] | null
      batch_version?: string
      /** Format: int64 */
      completed: number
      /** Format: int64 */
      failed: number
      generation: string
      /** Format: date-time */
      next_eligible?: string
      /** Format: int64 */
      overrides: number
      owner_instance_id?: string
      owner_renderer?: string
      phase?: string
      reason?: string
      /** Format: int64 */
      remaining: number
      revision: string
      /** Format: int64 */
      total: number
      version: string
    }
    RecoveryBody: {
      confirmed: boolean
      plan?: components['schemas']['RecoveryPlan']
      version: string
    }
    RecoveryPlan: {
      backup_path: string
      in_progress: boolean
      original_code: string
      profile_id: string
      profile_key: string
      /** Format: date-time */
      started_at: string
    }
    RecoveryResponse: {
      backup_path?: string
      plan: components['schemas']['RecoveryPlan']
      recreated: boolean
      version: string
    }
    ReturnedWindow: {
      /** Format: int64 */
      count: number
      /** Format: int64 */
      limit: number
      /** Format: int64 */
      offset: number
    }
    ReviewBody: {
      expected_revision: string
      version: string
    }
    ReviewOperation: {
      active: boolean
      /** Format: int64 */
      affected_count: number
      after?: string
      before?: string
      label: string
      operation_id: string
      taxonomy_effect?: string
      type: string
    }
    ReviewResponse: {
      active_operations: components['schemas']['ReviewOperation'][] | null
      inactive_operations: components['schemas']['ReviewOperation'][] | null
      operation_id?: string
      pending: components['schemas']['PendingSummary']
      revision: string
      targets?: components['schemas']['ReviewTarget'][] | null
      version: string
      window: components['schemas']['ReturnedWindow']
    }
    ReviewTarget: {
      category: string
      date: string
      hidden: boolean
      merchant: string
    }
    ReviewTargetsBody: {
      expected_revision: string
      operation_id: string
      version: string
      window: components['schemas']['Window']
    }
    RevisionBody: {
      expected_revision: string
      query: string
      selection?: string
      version: string
      window: components['schemas']['Window']
    }
    SelectionDisposition: {
      kind: string
      value: string
    }
    Statistics: {
      /** Format: int64 */
      count: number
      currency: string
      in: components['schemas']['Money']
      net: components['schemas']['Money']
      out: components['schemas']['Money']
      /** Format: int32 */
      scale: number
    }
    TransitionBody: {
      action: string
      filters?: components['schemas']['TransitionFilters']
      query: string
      search?: string
      selection?: string
      target?: components['schemas']['TransitionTarget']
      window: components['schemas']['Window']
    }
    TransitionDateRange: {
      /** Format: date */
      end: string
      /** Format: date */
      start: string
    }
    TransitionFilters: {
      date_range?: components['schemas']['TransitionDateRange']
      show_hidden: boolean
      show_transfers: boolean
    }
    TransitionTarget: {
      identity: string
      kind: string
    }
    ViewBody: {
      query: string
      selection?: string
      window: components['schemas']['Window']
    }
    ViewMetadata: {
      grouping: string
      mode: string
      search?: string
      sort_direction: string
      sort_field: string
      time_granularity: string
    }
    Warning: {
      code: string
      detail: string
    }
    Window: {
      /**
       * Format: int64
       * @default 200
       */
      limit: number
      /**
       * Format: int64
       * @default 0
       */
      offset: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  bootstrap: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Bootstrap']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  listProfiles: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProfileCatalogResponse']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  createProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileCreateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProfileResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  activateProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileActivateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProfileResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  profileBootstrap: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Bootstrap']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  cancelNewProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileCancelBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProfileCancelResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  commitProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CommitBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  projectProfileDuplicates: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DuplicateBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DuplicateResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  editorCatalog: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EditorCatalogBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorCatalogResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  mutateProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MutationBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  startProfileOnboarding: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingStartBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnboardingStatusResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  cancelProfileOnboarding: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingCancelBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnboardingStatusResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  profileOnboardingStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
        attempt_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnboardingStatusResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  submitProfileOnboarding: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingSubmitBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnboardingStatusResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  refreshProvider: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderRefreshBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderRefreshResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  confirmProviderRefresh: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderConfirmationBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderRefreshResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  providerStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderStatusResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  providerWriteStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderWriteStatusResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  pauseProviderWrite: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderWriteControlBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderWriteResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  reconcileProviderWrite: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderWriteReconcileBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderWriteResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  confirmProviderWriteReconcile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderWriteConfirmationBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderWriteResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  resumeProviderWrite: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProviderWriteControlBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderWriteResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  recoverProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecoveryBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  redoProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  reviewProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  reviewProfileTargets: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewTargetsBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  undoProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MutationResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  projectView: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ViewBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Projection']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  transitionView: {
    parameters: {
      query?: never
      header?: never
      path: {
        profile_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionBody']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Projection']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
}
