version: "2"
run:
  timeout: 3m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
formatters:
  enable:
    - gofmt
    - goimports
