"""
Centralized category definitions for moneyflow.

This module provides built-in category structure (chosen to ease integration
with Monarch Money) and supports custom categories via ~/.moneyflow/config.yaml.

The category system supports:
- Built-in default categories and groups
- Custom categories added to existing groups
- Custom category groups
- Renaming categories to match your finance platform
- Moving categories between groups
"""

import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import yaml

from .file_utils import UntrustedFileError, open_verified_no_follow, secure_atomic_write

logger = logging.getLogger(__name__)


def category_slug(name: str) -> str:
    """Normalize a category or group name to its persistent lowercase id.

    Config-backed backends (e.g. SimpleFIN) regenerate ids from names with
    this algorithm each session while transactions retain previously assigned
    ids, so its output must never change — including the ASCII-only stripping
    of non-ASCII characters ("Café" → "caf"). Use category_equivalence_key
    for comparing names, and stable_category_id for CSV import ids.
    """
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def category_equivalence_key(name: str) -> str:
    """Normalize a category name for equivalence comparison.

    Unicode-aware, unlike category_slug: distinct non-Latin names produce
    distinct keys instead of all collapsing to the empty string. This is the
    single normalization used by duplicate-category detection across CSV
    import, configuration, and TUI creation.
    """
    key = re.sub(r"\W+", "_", name.lower())
    return re.sub(r"_+", "_", key).strip("_")


def stable_category_id(name: str) -> str:
    """Return the canonical id for categories generated by CSV import.

    CSV-imported ids are new in this backend (no legacy databases exist), so
    they use the Unicode-aware key with a ``cat_`` prefix. Equivalence with
    ids from other surfaces must be checked by comparing
    ``category_equivalence_key`` of the names, not the ids.
    """
    key = category_equivalence_key(name)
    return f"cat_{key}" if key else "cat_uncategorized"


# Built-in default category groups
# These defaults are chosen to ease integration with Monarch Money and work well
# for most personal finance platforms.
# Source: Based on Monarch Money's category structure (as of 2025-01)
#
# Each group includes a top-level category with the same name for items that don't
# fit exactly into subcategories (e.g., "Business" category in Business group)
DEFAULT_CATEGORY_GROUPS: Dict[str, List[str]] = {
    "Income": [
        "Income",
        "Paychecks",
        "Interest",
        "Business Income",
        "Other Income",
    ],
    "Gifts & Donations": [
        "Gifts & Donations",
        "Charity",
        "Gifts",
    ],
    "Auto & Transport": [
        "Auto & Transport",
        "Auto Payment",
        "Public Transit",
        "Gas",
        "Auto Maintenance",
        "Parking & Tolls",
        "Taxi & Ride Shares",
    ],
    "Housing": [
        "Housing",
        "Mortgage",
        "Rent",
        "Home Improvement",
    ],
    "Bills & Utilities": [
        "Bills & Utilities",
        "Garbage",
        "Water",
        "Gas & Electric",
        "Internet & Cable",
        "Phone",
    ],
    "Food & Dining": [
        "Food & Dining",
        "Groceries",
        "Restaurants & Bars",
        "Coffee Shops",
    ],
    "Travel & Lifestyle": [
        "Travel & Lifestyle",
        "Travel & Vacation",
        "Entertainment & Recreation",
        "Personal",
        "Pets",
        "Fun Money",
    ],
    "Shopping": [
        "Shopping",
        "Clothing",
        "Furniture & Housewares",
        "Electronics",
    ],
    "Children": [
        "Children",
        "Child Care",
        "Child Activities",
    ],
    "Education": [
        "Education",
        "Student Loans",
    ],
    "Health & Wellness": [
        "Health & Wellness",
        "Medical",
        "Dentist",
        "Fitness",
    ],
    "Financial": [
        "Financial",
        "Loan Repayment",
        "Financial & Legal Services",
        "Financial Fees",
        "Cash & ATM",
        "Insurance",
        "Taxes",
    ],
    "Uncategorized": [
        "Uncategorized",
        "Check",
        "Miscellaneous",
    ],
    "Business": [
        "Business",
        "Advertising & Promotion",
        "Business Utilities & Communication",
        "Employee Wages & Contract Labor",
        "Business Travel & Meals",
        "Business Auto Expenses",
        "Business Insurance",
        "Office Supplies & Expenses",
        "Office Rent",
        "Postage & Shipping",
    ],
    "Transfers": [
        "Transfers",
        "Transfer",
        "Credit Card Payment",
        "Balance Adjustments",
    ],
}


def _get_config_path(
    base_dir: Optional[Union[str, Path]] = None, filename: str = "config.yaml"
) -> Path:
    base = Path(base_dir) if base_dir else Path.home() / ".moneyflow"
    return base / filename


class ConfigReadError(Exception):
    """An existing, trusted config file could not be read or parsed.

    Distinct from a missing or empty file: callers that rewrite the config
    must abort rather than treat an unreadable file as empty and overwrite
    the user's settings (and any retained alias records) with defaults.

    Files rejected as *untrusted* (symlink/reparse point, foreign owner,
    group/other writable) do not raise this — their contents were never the
    user's data, and the atomic rewrite replaces the planted file, which is
    the desired remediation.
    """


def _load_yaml_strict(path: Path) -> dict:
    """Load a config file, raising ConfigReadError if a trusted one fails.

    The config is authoritative (category structure, alias remapping), so it
    must not be read through a planted symlink or reparse point, and must be
    owned by the current user and not writable by others — otherwise another
    local account could dictate how imports are categorized.
    open_verified_no_follow enforces that on the opened descriptor before any
    content is parsed.
    """
    if not path.exists():
        return {}
    try:
        fd = open_verified_no_follow(path)
    except UntrustedFileError as e:
        # Untrusted file: never the user's data, so there is nothing to
        # preserve and a rewrite remediates the planted file.
        logger.error(f"Refusing to trust config at {path}: {e}")
        return {}
    except OSError as e:
        # Ordinary I/O failure on a file that may well be the user's data
        # (transient EIO, descriptor exhaustion, locked file). Never treat
        # this as empty: the caller must abort rather than overwrite it.
        logger.error(f"Could not open config at {path}: {e}")
        raise ConfigReadError(str(path)) from e
    try:
        with os.fdopen(fd, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except Exception as e:
        logger.error(f"Failed to load YAML from {path}: {e}")
        raise ConfigReadError(str(path)) from e
    if data is None:
        # Genuinely empty file (or one holding only comments).
        return {}
    if not isinstance(data, dict):
        # A list or scalar at the root is a corrupt or foreign document, not
        # an empty config. Treating it as empty would let the next save
        # overwrite whatever the file actually holds.
        logger.error(f"Config at {path} is not a mapping ({type(data).__name__})")
        raise ConfigReadError(str(path))
    return data


def _load_yaml(path: Path) -> dict:
    """Load a config file, returning {} when it is missing or unreadable.

    For read-only callers that can safely fall back to defaults. Callers that
    rewrite the file must use _load_yaml_strict.
    """
    try:
        return _load_yaml_strict(path)
    except ConfigReadError:
        return {}


def _save_yaml(path: Path, data: dict) -> bool:
    try:
        payload = yaml.dump(data, default_flow_style=False, sort_keys=False)
        # Atomic replace via a securely created temp file. The destination
        # path is never opened for writing, so a planted symlink cannot
        # redirect the write to another file — the rename replaces the
        # symlink itself with a regular file.
        secure_atomic_write(path, payload.encode())
        return True
    except Exception as e:
        logger.error(f"Failed to save YAML to {path}: {e}")
        return False


def load_custom_categories(
    config_dir: Optional[Union[str, Path]] = None,
) -> Optional[Dict[str, Any]]:
    """
    Load custom category configuration from ~/.moneyflow/config.yaml.
    """
    config_path = _get_config_path(config_dir)

    if not config_path.exists():
        logger.debug(f"No config file at {config_path}")
        return None

    config = _load_yaml(config_path)
    if not config:
        logger.warning(f"Empty config file at {config_path}")
        return None

    version = config.get("version")
    if version != 1:
        logger.warning(f"Unsupported config.yaml version: {version} (expected 1)")
        return None

    categories_config = config.get("categories")
    if categories_config:
        logger.info(f"Loaded custom categories from {config_path}")
        return categories_config
    else:
        logger.debug(f"No categories section in {config_path}")
        return None


def merge_category_groups(
    defaults: Dict[str, List[str]], custom_config: Optional[Dict[str, Any]]
) -> Dict[str, List[str]]:
    """
    Merge custom category configuration with defaults.
    """
    import copy

    if not custom_config:
        return defaults

    merged = copy.deepcopy(defaults)

    group_renames = custom_config.get("rename_groups", {})
    if group_renames:
        for old_name, new_name in group_renames.items():
            if old_name in merged:
                merged[new_name] = merged.pop(old_name)
                logger.info(f"Renamed group: '{old_name}' → '{new_name}'")
            else:
                logger.warning(f"Cannot rename non-existent group: '{old_name}'")

    category_renames = custom_config.get("rename_categories", {})
    if category_renames:
        for group_name, categories in merged.items():
            merged[group_name] = [category_renames.get(cat, cat) for cat in categories]
        logger.info(f"Applied {len(category_renames)} category renames")

    add_to_groups = custom_config.get("add_to_groups", {})
    for group_name, new_categories in add_to_groups.items():
        if group_name in merged:
            for cat in new_categories:
                if cat not in merged[group_name]:
                    merged[group_name].append(cat)
            logger.info(f"Added {len(new_categories)} categories to {group_name}")
        else:
            logger.warning(f"Cannot add to non-existent group: {group_name}")

    custom_groups = custom_config.get("custom_groups", {})
    for group_name, categories in custom_groups.items():
        if group_name in merged:
            logger.warning(f"Custom group '{group_name}' already exists, skipping")
        else:
            merged[group_name] = list(categories)
            logger.info(f"Added custom group: {group_name} with {len(categories)} categories")

    moves = custom_config.get("move_categories", {})
    for category_name, new_group in moves.items():
        if new_group not in merged:
            logger.warning(f"Cannot move '{category_name}' to non-existent group: {new_group}")
            continue

        old_group_name = None
        for group_name, categories in merged.items():
            if category_name in categories:
                categories.remove(category_name)
                old_group_name = group_name
                logger.debug(f"Removed '{category_name}' from {group_name}")
                break

        if category_name not in merged[new_group]:
            merged[new_group].append(category_name)
        logger.info(f"Moved '{category_name}' from {old_group_name} to {new_group}")

    return merged


def convert_api_categories_to_groups(
    categories_data: Dict[str, Any], groups_data: Dict[str, Any]
) -> Dict[str, List[str]]:
    """
    Convert API category format to simple group → [categories] mapping.
    """
    result: Dict[str, List[str]] = {}

    group_id_to_name = {}
    for group in groups_data.get("categoryGroups", []):
        group_id_to_name[group["id"]] = group["name"]

    for cat in categories_data.get("categories", []):
        group_data = cat.get("group") or {}
        group_id = group_data.get("id")

        if group_id and group_id in group_id_to_name:
            group_name = group_id_to_name[group_id]
            category_name = cat["name"]

            if group_name not in result:
                result[group_name] = []
            result[group_name].append(category_name)

    return result


def save_categories_to_config(
    category_groups: Dict[str, List[str]], config_dir: Optional[Union[str, Path]] = None
) -> bool:
    """
    Save fetched category structure to config.yaml.

    Returns:
        True if save succeeded, False otherwise.
    """
    config_path = _get_config_path(config_dir)
    try:
        config = _load_yaml_strict(config_path)
    except ConfigReadError:
        logger.error(f"Refusing to overwrite unreadable config: {config_path}")
        return False

    config["version"] = 1
    config["fetched_categories"] = category_groups

    saved = _save_yaml(config_path, config)

    if saved:
        logger.info(
            f"Saved {len(category_groups)} category groups "
            f"({sum(len(cats) for cats in category_groups.values())} categories) "
            f"to {config_path}"
        )
    return saved


def build_category_to_group_mapping(category_groups: Dict[str, List[str]]) -> Dict[str, str]:
    """
    Build reverse mapping from category name to group name.
    """
    category_to_group = {}
    for group_name, categories in category_groups.items():
        for category in categories:
            category_to_group[category] = group_name
    return category_to_group


def save_categories_to_profile(
    category_groups: Dict[str, List[str]], profile_dir: Union[str, Path]
) -> bool:
    """
    Save category structure to profile-local config.yaml.
    """
    config_path = Path(profile_dir) / "config.yaml"
    try:
        config = _load_yaml_strict(config_path)
    except ConfigReadError:
        logger.error(f"Refusing to overwrite unreadable config: {config_path}")
        return False

    config["version"] = 1
    config["fetched_categories"] = category_groups

    if _save_yaml(config_path, config):
        logger.info(
            f"Saved {len(category_groups)} category groups "
            f"({sum(len(cats) for cats in category_groups.values())} categories) to {config_path}"
        )
        return True
    return False


PENDING_ALIASES_KEY = "pending_category_aliases"


def save_pending_category_aliases(
    profile_dir: Union[str, Path], aliases: List[Tuple[Any, ...]]
) -> bool:
    """Durably record category-alias records awaiting backend persistence.

    Stored in the profile config so alias records the backend failed to
    confirm survive an application exit and are retried on the next run.
    An empty list removes the key.
    """
    config_path = Path(profile_dir) / "config.yaml"
    try:
        config = _load_yaml_strict(config_path)
    except ConfigReadError:
        logger.error(f"Refusing to overwrite unreadable config: {config_path}")
        return False
    if aliases:
        config[PENDING_ALIASES_KEY] = [list(alias) for alias in aliases]
    else:
        if PENDING_ALIASES_KEY not in config:
            return True
        config.pop(PENDING_ALIASES_KEY, None)
    return _save_yaml(config_path, config)


def load_pending_category_aliases(profile_dir: Union[str, Path]) -> List[Tuple[Any, ...]]:
    """Load durably retained alias records as (source, target, name, revision).

    Records written before revisions existed default to revision 0, which is
    older than any recorded backend revision, so they are treated as stale
    rather than replayed over newer mappings.
    """
    config = _load_yaml(Path(profile_dir) / "config.yaml")
    raw = config.get(PENDING_ALIASES_KEY, [])
    aliases: List[Tuple[Any, ...]] = []
    if not isinstance(raw, list):
        return aliases
    for item in raw:
        if (
            isinstance(item, (list, tuple))
            and len(item) in (3, 4)
            and all(isinstance(part, str) for part in item[:3])
        ):
            revision = item[3] if len(item) == 4 and isinstance(item[3], int) else 0
            aliases.append((item[0], item[1], item[2], revision))
    return aliases


def load_categories_from_profile(profile_dir: Union[str, Path]) -> Optional[Dict[str, List[str]]]:
    """
    Load category structure from profile-local config.yaml.
    """
    config_path = Path(profile_dir) / "config.yaml"

    if not config_path.exists():
        return None

    config = _load_yaml(config_path)
    if config and "fetched_categories" in config:
        fetched = config["fetched_categories"]
        logger.info(
            f"Loaded categories from {config_path}: {len(fetched)} groups, "
            f"{sum(len(cats) for cats in fetched.values())} categories"
        )
        return fetched

    return None


def get_effective_category_groups(
    config_dir: Optional[Union[str, Path]] = None,
) -> Dict[str, List[str]]:
    """
    Get category groups (LEGACY - for backward compatibility).
    """
    config_path = _get_config_path(config_dir)

    if config_path.exists():
        config = _load_yaml(config_path)
        if config and "fetched_categories" in config:
            fetched = config["fetched_categories"]
            logger.info(
                f"Using fetched categories from config.yaml: {len(fetched)} groups, "
                f"{sum(len(cats) for cats in fetched.values())} categories"
            )
            return fetched

    logger.info("Using built-in default categories")
    return DEFAULT_CATEGORY_GROUPS


def get_profile_category_groups(
    profile_dir: Optional[Union[str, Path]] = None,
) -> Dict[str, List[str]]:
    """
    Get category groups for a specific profile, falling back to defaults.
    """
    if profile_dir:
        categories = load_categories_from_profile(profile_dir)
        if categories:
            return categories

    logger.info("Using built-in default categories")
    return DEFAULT_CATEGORY_GROUPS


def format_categories_yaml(category_groups: Dict[str, List[str]]) -> str:
    """Format category groups as YAML string."""
    lines = []
    lines.append("# Current category hierarchy")
    lines.append("# Copy sections below into your config.yaml under 'categories:'\n")

    for group_name in sorted(category_groups.keys()):
        categories_list = category_groups[group_name]
        # Use quotes if group name has special chars
        if " " in group_name or "&" in group_name:
            lines.append(f'  "{group_name}":')
        else:
            lines.append(f"  {group_name}:")
        for cat in sorted(categories_list):
            # Use quotes if category has special chars
            if " " in cat or "&" in cat:
                lines.append(f'    - "{cat}"')
            else:
                lines.append(f"    - {cat}")
        lines.append("")  # Blank line between groups

    return "\n".join(lines)


def format_categories_readable(category_groups: Dict[str, List[str]]) -> str:
    """Format category groups as human-readable string."""
    lines = []
    lines.append("Current Category Hierarchy")
    lines.append("=" * 60)

    total_cats = sum(len(cats) for cats in category_groups.values())
    lines.append(f"Total: {len(category_groups)} groups, {total_cats} categories\n")

    for group_name in sorted(category_groups.keys()):
        categories_list = category_groups[group_name]
        lines.append(f"\n{group_name} ({len(categories_list)} categories):")
        for cat in sorted(categories_list):
            lines.append(f"  - {cat}")

    return "\n".join(lines)


def categories_dict_to_config_groups(categories: Dict[str, Dict[str, str]]) -> Dict[str, List[str]]:
    """
    Reverse-engineer ``category_groups_config`` format from a ``self.categories`` dict.

    ``self.categories`` maps ``category_id -> {name, group, group_id, group_type}``.
    This converts it back to the config format ``{group_name: [cat_name, ...]}``.

    Args:
        categories: The ``self.categories`` dict from DataManager.

    Returns:
        Dict suitable for ``save_categories_to_config()`` or
        ``save_categories_to_profile()``.
    """
    groups: Dict[str, List[str]] = {}
    for cat_data in categories.values():
        group_name = cat_data.get("group", "Uncategorized")
        cat_name = cat_data.get("name", "")
        if not cat_name:
            continue
        groups.setdefault(group_name, []).append(cat_name)
    # Deduplicate category names within each group (shouldn't happen, but be safe)
    for group_name in groups:
        groups[group_name] = list(dict.fromkeys(groups[group_name]))
    return groups
